### ISSUE TITLE
acceptOffer in MarketplaceCore has <= instead of >= for endTime

### ISSUE THREAD

**Issue by P3rrin01** [EvoVerses/contracts#2]
This line:
require(sale.endTime <= block.timestamp, "MarketplaceCore: Offer is over");

should be:
require(sale.endTime >= block.timestamp, "MarketplaceCore: Offer is over");

This is causing us to not be able to accept offers.

**Comment by dirtycajunrice** [comment]
Hah. Good catch. Will update.
